### PR TITLE
install python3 only when ansible_system == Linux

### LINKED ISSUE #109: Do not run Python bootstrap prepare tasks in vagrant plugin for WinRM connections
Can you please add the following when condition at the end of the vagrant [prepare.yml](https://github.com/ansible-community/molecule-plugins/blob/main/src/molecule_plugins/vagrant/playbooks/prepare.yml) file:
`when: ansible_connection != 'winrm'`

Background: I am using Linux and Windows hosts for my molecule test. Unfortunately the Windows hosts always fail because of this command.

Or are there any better ideas.

Thank you

### PR DESCRIPTION
**Pull request by konstruktoid**
This PR:
- install python3 only when `ansible_system == Linux`
- closes #109

### CODE REVIEW

**Comment by apatard** [comment]
thanks for doing it. I'm wondering : Are there some other connection type needing the same "fix" ?

**Review by apatard — APPROVED** [review]

**Comment by konstruktoid** [comment]
I guess everything that installs things using Linux package managers.
I know Windows enough regarding e.g ansibile `package:`

**Comment by zhan9san** [comment]
> Are there some other connection type needing the same "fix" ?

Like @konstruktoid mentioned, I suggest to use [ansible.builtin.package](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html), and add a condition `ansible_system == Linux`

It needs enable `gather_facts`.

**Comment by konstruktoid** [comment]
replaced `raw:` with `package:`

**Comment by apatard** [comment]
> replaced `raw:` with `package:`

why ? it's the bootstrap phase which means that on systems python may even installed, that's why it's using raw.

**Comment by konstruktoid** [comment]
> why ? it's the bootstrap phase which means that on systems python may even _not_ be installed, that's why it's using raw.

but they all do? all checks passed, and i assumed this was to ensure that python3 was installed.
but no worries, if it's an issue then i'll revert it back

**Comment by konstruktoid** [comment]
reverted back to `raw:`

but shouldn’t the tests had failed due to the alpine boxes and `package:` then?

**Comment by apatard** [comment]
btw, if we're enabling gather_facts, should we use gather_subset too ?

**Comment by konstruktoid** [comment]
don't merge, if we assume a system doesn't have python installed, gather_facts wont work

**Comment by zhan9san** [comment]
LGTM

Thanks for your patience@konstruktoid 

If you don't have concerns, we can merge it.@apatard

**Comment by apatard** [comment]
@konstruktoid thanks for bearing with me. Merging it now.

**Pull request merged**
