### PR TITLE
Update pre-commit hooks (broken, needs bugfix of linter)

### PR DESCRIPTION
**Pull request by ssbarnea**

### CODE REVIEW

**Comment by apatard** [comment]
@ssbarnea is there a bug open on -lint side for this issue ?

**Comment by ssbarnea** [comment]
@apatard No need, it is https://github.com/ansible/ansible-lint/issues/3344

**Comment by apatard** [comment]
Should we try again with -lint 6.16 ?

**Comment by apatard** [comment]
I guess that this PR is now obsolete, since I merged  PR 137. So, closing this one.

**Pull request closed without merging**
