### PR TITLE
Install rsync as dependency

### PR DESCRIPTION
**Pull request by truestory1**
this is required for [syncronize](src/molecule_plugins/docker/playbooks/create.yml#L57) module, which is rsync [wrapper](https://docs.ansible.com/ansible/latest/collections/ansible/posix/synchronize_module.html#synopsis)

### CODE REVIEW

**Comment by truestory1** [comment]
@ssbarnea , but we already are in ansible-community/molecule-plugins repo.

**Comment by ssbarnea** [comment]
Oops, I got confused myself. Regarding rsync, I know that this is needed in order to allow use of synchronize with the container but I am not sure if that needed or desired to be in default template.

I will ask few others users of the docker plugin.

**Comment by apatard** [comment]
Was there an agreement about this PR ? It make sense to have it I guess. Nevertheless, I'm always using pre-built images so I can't comment.

**Comment by zhan9san** [comment]
I agree to add `rsync`.

**Review by zhan9san — APPROVED** [review]

**Pull request merged**
