### PR TITLE
Perform linting on Ansible playbooks

### LINKED ISSUE #100: molecule-podman converge.yml playbook linting issues a warning
Running ansible-lint on current converge.yml playbook from the podman plugin leads to:

```
risky-file-permissions: File permissions unset or incorrect. (warning)
molecule/default/converge.yml:6 Task/Handler: Copy something to test use of synchronize module
```

So, I'm opening a bug to not forget to fix it.

### PR DESCRIPTION
**Pull request by konstruktoid**
This PR:
- Adds `experimental` to ansible-lint skip_list
- Perform linting on Ansible playbooks
- Closes #100

### CODE REVIEW

**Comment by konstruktoid** [comment]
another Galaxy error, https://github.com/ansible-community/molecule-plugins/actions/runs/4179174587/jobs/7238820200#step:6:72

**Comment by apatard** [comment]
oh, thanks for doing it ! Btw, I already did some fixes in the past: https://github.com/ansible-community/molecule-plugins/pull/90. Since your PR is doing more, I'm happy to close mine. Nevertheless, I'm not seeing any alignment fixes for molecule/test-podman/verify.yml. Has this already been fixed ?

And for the galaxy failure, looks like we're getting it more and more. Not sure we can do anything. Maybe using GHA caching ? but I'm not sure it's a good idea or if it'll work.

**Comment by konstruktoid** [comment]
So sorry @apatard, I totally missed #90 ... and I also missed `molecule/test-podman/verify.yml` but that should be fixed now.

**Comment by apatard** [comment]
> So sorry @apatard, I totally missed #90 ... and I also missed `molecule/test-podman/verify.yml` but that should be fixed now.

No worry. All that matter is that the lint issues are getting fixed. I've closed my PR.

**Comment by apatard** [comment]
pushed an extra commit to hopefully finishing linting issues. I hope you don't mind. Also, realized after pushing that this PR was about playbooks only, so fill free to kill my commit if wanted and I'll send a new PR

**Comment by konstruktoid** [comment]
All good @apatard

**Comment by konstruktoid** [comment]
I believe there's a need to restart a lot of tests due to yet more Galaxy issues, `ansible-playbook -i'127.0.0.1,' -c local ./src/molecule_plugins/podman/playbooks/validate-dockerfile.yml` works locally (tm).

**Comment by apatard** [comment]
yeah, same here. I don't remember having issues with it on my test vm... but on gha, it seems to happen a lot. I'm disappointed that there's no error message. I thought we were seeing them previously (unless I'm mixing with ansible-lint or molecule ci)

**Comment by konstruktoid** [comment]
Yeah, previously (or maybe because of other causes) there was proper timeout error messages but this just fails.

**Review by apatard — APPROVED** [review]
hm. yeah, it seems a good idea to skip experimental checks.

**Comment by apatard** [comment]
fyi, added a label to make the latest check green.

**Comment by konstruktoid** [comment]
> fyi, added a label to make the latest check green.

thanks, i dont have that power

**Pull request merged**
