### PR TITLE
doc: add absent molecule plugins

### PR DESCRIPTION
**Pull request by nnzv**
Hey, just wanted to let you know that I noticed a few molecule plugins are missing. So, I went ahead and made a pull request to add them. Let me know what you think and if you have any suggestions.

### CODE REVIEW

**Comment by apatard** [comment]
Hi,
There's already a pending PR for that: https://github.com/ansible-community/molecule-plugins/pull/91/ . It's stuck atm due to missing review.

**Comment by zhan9san** [comment]
Thanks for your patience.

Overall, there is nothing wrong in this PR.

I'll take a look at the failed ci job tomorrow.

**Comment by apatard** [comment]
@zhan9san please don't lose time on looking at the CI. It's known to be failing due to various issues. The lint ones are fixed by a pending PR and the rest of issues are supposed to be galaxy timeouts and until it's fixed on galaxy side, there's not a lot to do...
And for this PR, I think it should be closed, since there's an other PR for the exact same issue. I only didn't close it because I think it should rather be done by the person opening the PR.

**Comment by zhan9san** [comment]
Hi @nnzv 

Thanks for your work.

This issue has been addressed in #91 
I'll close this PR.

**Pull request closed without merging**
