### PR TITLE
feature(Docker): Add support for `platform` parameter

### PR DESCRIPTION
**Pull request by dankow**
Pass `platform` value from `platforms.item` to `docker_container`. Example usage:
```
driver:
  name: docker
platforms:
  - name: test-01
    image: ...
    pre_build_image: true
    platform: linux/amd64
```

As suggested in the [docker_container documentation](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#ansible-collections-community-docker-docker-container-module), ignore the `platform` parameter when comparing state.

Addresses issue #94.

### CODE REVIEW

**Comment by ThomasSteinbach** [comment]
@dankow I am no reviewer but I would like to see your feature merged. I recognized, that some checks failed. Please fix following things, to hopefully get your PR merged:

* Prepend `feature` to the title of your PR. Like _feature(Docker): Add support for `plattform` parameter._
  It looks like the pipeline enforces Conventional Commits: https://www.conventionalcommits.org/en/v1.0.0/

**Comment by dankow** [comment]
@ThomasSteinbach Thanks for the hint, I've changed the PR title

**Comment by ThomasSteinbach** [comment]
@ssbarnea would it be possible to review/merge that PR.
Without that change Molecule actually didn't work on M1 Macs.
Thanks in advance.

**Comment by ssbarnea** [comment]
This needs fixing, failed even linting.

**Comment by dankow** [comment]
@ssbarnea - Correct me if I'm wrong, but aren't the linting failures and other failures in completely unrelated parts of the code?

**Comment by ThomasSteinbach** [comment]
@ssbarnea I have to agree to @dankow , none of the current pull requests passes the checks.
The output of those checks seems to me quite unreleated to the changes in this PR, e.g. linting:

```
yaml[indentation]: Wrong indentation: expected at least 3
test/gce/scenarios/windows/verify.yml:8
```

... or in pytests ...

```
STDERR: ERROR! couldn't resolve module/action 'containers.podman.podman_image'
```

I don't know if rebasing to main would help. Does it @ssbarnea ?

**Comment by apatard** [comment]
> @ssbarnea I have to agree to @dankow , none of the current pull requests passes the checks. The output of those checks seems to me quite unreleated to the changes in this PR, e.g. linting:
> 
> ```
> yaml[indentation]: Wrong indentation: expected at least 3
> test/gce/scenarios/windows/verify.yml:8
> ```
> 
> ... or in pytests ...
> 
> ```
> STDERR: ERROR! couldn't resolve module/action 'containers.podman.podman_image'
> ```
> 
> I don't know if rebasing to main would help. Does it @ssbarnea ?

I can't talk for @ssbarnea who is the maintainer of this project but what I can say:
- there are lint errors with main branch: https://github.com/ansible-community/molecule-plugins/pull/101
- there are ansible-galaxy timeouts leading to CI failures : https://github.com/ansible-community/community-topics/issues/206

So, imho, the timeouts has to be fixed first, then PR101 tests can be restarted and hopefully this PR merged. Once done, main branch should have CI in green. Then, pending pull requests will have to be rebased and hopefully may be merged if review is fine. Blindly merging PR without CI "because CI is broken" seems really bad practice to me...

**Comment by apatard** [comment]
@dankow Hi. thanks to some other devs, the CI seems to be on happy side these days. Can you please rebase and check new CI status ?

**Comment by dankow** [comment]
@ssbarnea - now that the checks all pass, are there any barriers to merging this PR?

**Review by ssbarnea — APPROVED** [review]

**Pull request merged**
