### PR TITLE
Unbreak CI

### PR DESCRIPTION
**Pull request by apatard**
- Upgrade containers and boxes to use newer versions
- Remove create.yml/destroy.yml templates copied by molecule with molecule init for unlucky plugins
- Rename vagrant tests to avoid "import vagrant" in the test importing the test module instead of importing the vagrant module.
- Move the vagrant box_url testing to its own test to avoid failures in multi-node where it would be hard to know if the issue is with the test or with the box_url test.

### CODE REVIEW

**Review by matt-horwood-mayden — APPROVED** [review]
looks fine, can we merge

**Comment by apatard** [comment]
@matt-horwood-mayden well, a review from someone with write access is needed.

**Comment by matt-horwood-mayden** [comment]
@apatard yeah I know 😞 

@ ssbarnea could you have a look at this PR please?

**Comment by cnfrancis** [comment]
hello! gentle bump on this @ssbarnea

**Review by oraNod — APPROVED** [review]
@apatard Thanks. I've requested a review from @ssbarnea as he is more familiar with this repo but it LGTM. If we don't get another ack soon-ish I'll merge as this seems like it's blocking stuff.

**Review by ssbarnea — APPROVED** [review]

**Pull request merged**
