### PR TITLE
enhancement: add fqcn to cookicutter files of ec2, containers and docker

### PR DESCRIPTION
**Pull request by bernd-mueller-1**

### CODE REVIEW

**Comment by bernd-mueller-1** [comment]
How can the failed tox / lint be fixed? this test also failes with the same messages without my changes.

**Comment by apatard** [comment]
> How can the failed tox / lint be fixed? this test also failes with the same messages without my changes.

Sorry, I failed to find some time to look at these lint issues. I'll try to find some free time today / this week as it would be nice to get a new version of the plugins out at worse next week [ in order to get a version with fixed/working vagrant plugin ].

**Review by apatard — CHANGES_REQUESTED** [review]
note: I won't comment the use of community.aws vs amazon.aws since I'm not aws user. I've no idea which collection is the right one to use.

If you rebase the lint errors should be gone. Nevertheless, this PR needs some extra work:
- Remove the corresponding lines in  .ansible-lint-ignore (fqcn errors for test/roles/dockerplugin/, test/roles/ec2plugin, test/roles/containersplugin/)
- Then check if some new fqcn related errors all gone
- fix the requirement.yml to use amazon.aws
- check that the doc is mentioning the actually used collection (community.aws vs amazon.aws).

**Comment by bernd-mueller-1** [comment]
@apatard Thanks for your fix and the hints.

**Review by apatard — APPROVED** [review]
Thanks for the PR and for fixing the few comments I had.

**Pull request merged**
